app:
  name: wechatgpt

server:
  port: 80
  servlet:
    context-path:

openai:
  organization:
    model: gpt-3.5
#  model: gpt-3.5-turbo-0301
#  model: gpt-4
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions

spring:
  redis:
    port: 6379
    host: localhost
    password: 12345678
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 10000

log:
  level: debug
  dir: /var/log/${app.name}/