server:
  port: 80
  servlet:
    context-path:

openai:
  organization:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions

spring:
  redis:
    port: 6379
    host: localhost
    password: 12345678
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 10000
